main:main.o narcissusNumber.o helloworld.o oneAddto100.o
	gcc main.o narcissusNumber.o helloworld.o oneAddto100.o
main.o:main.c
	gcc -c main.c
narcissusNumber.o:narcissusNumber.c
	gcc -c narcissusNumber.c
helloworld.c:helloworld.c
	gcc -c helloworld.c
oneAddto100.o:oneAddto100.c
	gcc -c oneAddto100.c
clean:
	rm mian* .o
